spring.application.name=integration
spring.datasource.url=postgresql://postgres:HrrnvdzMRmmLCqENdVKtQXWrvZsVoEip@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=HrrnvdzMRmmLCqENdVKtQXWrvZsVoEip
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.datetime-format=yyyy-MM-dd'T'HH:mm:ss'Z'
